version: "3"
services:
    peacockserver:
        ports:
            - 4444:${PORT:-3000}
        build: .
        volumes:
        - ./data/${BRANCH:-master}/:/Peacock
        - ./plugins:/Plugins
        environment:
          - PORT=${PORT:-3000}
          - BRANCH=${BRANCH:-master}
